# Generated by Django 5.1.6 on 2025-02-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
